apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: openmp-engine-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: openmp-engine
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
