apiVersion: apps/v1
kind: Deployment
metadata:
  name: socket-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: socket-server
  template:
    metadata:
      labels:
        app: socket-server
    spec:
      serviceAccountName: default  # ou service account com permissão
      containers:
        - name: socket-server
          image: pedroblome/pspd_trabalho:socket
          imagePullPolicy: Always
          env:
           - name: KUBECONFIG
             value: /root/.kube/config
         volumeMounts:
           - name: kubeconfig
             mountPath: /root/.kube
          ports:
            - containerPort: 65431
          env:
            - name: KUBECONFIG
              value: /var/run/secrets/kubernetes.io/serviceaccount/token
      volumes:
        - name: kubeconfig
          configMap:
            name: kubeconfig

---
apiVersion: v1
kind: Service
metadata:
  name: socket-server-service
spec:
  type: NodePort
  selector:
    app: socket-server
  ports:
    - port: 65431
      targetPort: 65431
      nodePort:  30080
